const questions=[
{id:1,t:'Constitution & Governance',q:'Which principle best describes constitutionalism?',o:['Government by administrative convenience','Government limited by constitutional rules','Rule by majority without limits','Judicial control of every policy'],a:1,e:'Constitutionalism means government power is structured and limited by constitutional rules.'},
{id:2,t:'Governance',q:'Which is most directly associated with accountable public administration?',o:['Opacity','Answerability and enforceability','Unlimited discretion','Secrecy'],a:1,e:'Accountability combines answerability with mechanisms that can impose consequences where appropriate.'},
{id:3,t:'Federalism',q:'Nepal has how many levels of government under its Constitution?',o:['Two','Three','Four','Five'],a:1,e:'Nepal has federal, provincial and local levels of government.'},
{id:4,t:'Public Administration',q:'POSDCORB is associated with which field?',o:['Public administration/management','Agronomy','Macroeconomics','Constitutional law'],a:0,e:'POSDCORB is a classic mnemonic covering management functions such as planning and organizing.'},
{id:5,t:'Reasoning',q:'If all A are B and all B are C, which conclusion follows?',o:['Some C are not A','All A are C','No A are C','All C are A'],a:1,e:'This is a standard transitive syllogism: A ⊆ B and B ⊆ C, therefore A ⊆ C.'},
{id:6,t:'Governance',q:'Which is a core purpose of e-governance?',o:['Increase paperwork','Improve access and service delivery using digital systems','Eliminate all human decisions','Replace the Constitution'],a:1,e:'E-governance uses digital technologies to improve government processes, access and services.'},
{id:7,t:'Constitution',q:'The rule of law primarily means:',o:['Officials are above law','Law applies through arbitrary preference','Public power is exercised under law','Only courts must follow law'],a:2,e:'Rule of law requires public authority to operate within a lawful framework.'},
{id:8,t:'Economy',q:'Inflation refers to:',o:['A sustained general rise in prices','A fall in all wages','Only a rise in food prices','A fall in money supply'],a:0,e:'Inflation is a sustained increase in the general price level.'},
{id:9,t:'Ethics',q:'A conflict of interest occurs when:',o:['Two departments cooperate','Private interests can improperly influence official duties','An officer takes leave','A policy is reviewed'],a:1,e:'The key issue is the risk that personal interests interfere, or appear to interfere, with official responsibilities.'},
{id:10,t:'Current Affairs Method',q:'For an official-exam current-affairs fact, the strongest primary source is generally:',o:['An anonymous social post','A copied blog','The responsible government/official institution','A random comment'],a:2,e:'Primary institutional sources should be preferred for official facts, while independent reporting can provide context.'}
];
let state=JSON.parse(localStorage.nomLok||'{"correct":0,"attempts":0,"mistakes":[],"mock":null}');
function save(){localStorage.nomLok=JSON.stringify(state);update();}
function update(){document.getElementById('readiness').textContent=Math.min(99,Math.round((state.correct/Math.max(1,state.attempts))*100))+'%';renderMistakes()}
function show(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='practice')renderQuiz();if(id==='review')renderMistakes();window.scrollTo(0,0)}
function renderQuiz(){let qs=questions.slice(0,5);document.getElementById('qCount').textContent=qs.length+' questions';document.getElementById('quiz').innerHTML=qs.map(q=>'<article class="question"><p class="eyebrow">'+q.t+'</p><h3>'+q.q+'</h3><div class="options">'+q.o.map((x,i)=>'<button onclick="answer('+q.id+','+i+',this)">'+String.fromCharCode(65+i)+'. '+x+'</button>').join('')+'</div><div id="f'+q.id+'" class="feedback hidden"></div></article>').join('')}
function answer(id,i,btn){let q=questions.find(x=>x.id===id),f=document.getElementById('f'+id);state.attempts++;if(i===q.a){state.correct++;f.textContent='✓ Correct — '+q.e;f.style.borderLeft='3px solid var(--accent)'}else{if(!state.mistakes.includes(id))state.mistakes.push(id);f.textContent='✗ Review — '+q.e;f.style.borderLeft='3px solid #ff8b8b'}f.classList.remove('hidden');btn.parentElement.querySelectorAll('button').forEach(b=>b.disabled=true);save()}
function renderMistakes(){let el=document.getElementById('mistakes');if(!el)return;if(!state.mistakes.length){el.innerHTML='<div class="panel"><p>No mistakes saved yet. Complete a practice drill and your weak questions will appear here.</p></div>';return}el.innerHTML=state.mistakes.map(id=>{let q=questions.find(x=>x.id===id);return '<article class="question"><p class="eyebrow">'+q.t+'</p><h3>'+q.q+'</h3><div class="feedback">Answer: '+q.o[q.a]+'<br>'+q.e+'</div></article>'}).join('')}
function startMock(){let qs=[...questions].sort(()=>Math.random()-.5).slice(0,Math.min(10,questions.length));document.getElementById('mockBox').innerHTML='<div class="question"><p class="eyebrow">MINI MOCK</p><h3>'+qs.map((q,i)=>(i+1)+'. '+q.q+'<br><small>'+q.o.map((x,j)=>String.fromCharCode(65+j)+') '+x).join(' &nbsp; ')+'</small>').join('<hr>')+'</h3><p class="feedback">MVP mode: production version will add timer, autosave, negative marking rules, analytics and server-side scoring.</p></div>'}
update();
